06-rails/tunr/config/routes.rb
Tunr::Application.routes.draw do
  get '/artist_facts/edit_all' => 'artist_facts#edit_all',
      :as => 'edit_all_artist_facts'
  post '/artist_facts/update_all' => 'artist_facts#update_all'
  resources :artist_facts

  root :to => 'pages#home'

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'

  resources :users, :except => [:edit] do
    collection do
      get 'edit'
    end
  end
end

06-rails/tunr/app/models/album.rb
# == Schema Information
#
# Table name: albums
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  image      :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Album < ActiveRecord::Base
  attr_accessible :name, :image
  has_many :songs
  has_many :artists, :through => :songs
end

06-rails/tunr/app/models/artist.rb
# == Schema Information
#
# Table name: artists
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  image      :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Artist < ActiveRecord::Base
  attr_accessible :name, :image
  has_many :songs
  has_many :albums, :through => :songs
end

06-rails/tunr/app/models/artist_fact.rb
class ArtistFact < ActiveRecord::Base
  attr_accessible :fact, :website
end

06-rails/tunr/app/models/genre.rb
# == Schema Information
#
# Table name: genres
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  image      :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Genre < ActiveRecord::Base
  attr_accessible :name, :image
  has_and_belongs_to_many :songs
end

06-rails/tunr/app/models/mixtape.rb
# == Schema Information
#
# Table name: mixtapes
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  user_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Mixtape < ActiveRecord::Base
  attr_accessible :name, :user_id
  belongs_to :user
  has_and_belongs_to_many :songs
end

06-rails/tunr/app/models/song.rb
# == Schema Information
#
# Table name: songs
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  image      :text
#  filename   :string(255)
#  artist_id  :integer
#  album_id   :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Song < ActiveRecord::Base
  attr_accessible :name, :image, :filename, :album_id, :artist_id
  belongs_to :album
  belongs_to :artist
  has_and_belongs_to_many :genres
  has_and_belongs_to_many :mixtapes
end

06-rails/tunr/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  name            :string(255)
#  image           :text
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  password_digest :string(255)
#  is_admin        :boolean          default(FALSE)
#

class User < ActiveRecord::Base
  has_secure_password

  attr_accessible :name, :image, :password, :password_confirmation
  has_many :mixtapes

  validates :image, :presence => true
  validates :name, :presence => true, :length => { :minimum => 2 }
end

06-rails/tunr/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  before_filter :authentication

  private
  def authentication
    @authenticated = User.find(session[:user_id]) unless session[:user_id].nil?
  end
end

06-rails/tunr/app/controllers/artist_facts_controller.rb
class ArtistFactsController < ApplicationController
  # GET /artist_facts
  # GET /artist_facts.json
  def index
    @artist_facts = ArtistFact.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @artist_facts }
    end
  end

  # GET /artist_facts/1
  # GET /artist_facts/1.json
  def show
    @artist_fact = ArtistFact.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @artist_fact }
    end
  end

  # GET /artist_facts/new
  # GET /artist_facts/new.json
  def new
    @artist_fact = ArtistFact.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @artist_fact }
    end
  end

  # GET /artist_facts/1/edit
  def edit
    @artist_fact = ArtistFact.find(params[:id])
  end

  def edit_all
    @artist_facts = ArtistFact.all
  end

  # POST /artist_facts
  # POST /artist_facts.json
  def create
    @artist_fact = ArtistFact.new(params[:artist_fact])

    respond_to do |format|
      if @artist_fact.save
        format.html { redirect_to @artist_fact, notice: 'Artist fact was successfully created.' }
        format.json { render json: @artist_fact, status: :created, location: @artist_fact }
      else
        format.html { render action: "new" }
        format.json { render json: @artist_fact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /artist_facts/1
  # PUT /artist_facts/1.json
  def update
    @artist_fact = ArtistFact.find(params[:id])

    respond_to do |format|
      if @artist_fact.update_attributes(params[:artist_fact])
        format.html { redirect_to @artist_fact, notice: 'Artist fact was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @artist_fact.errors, status: :unprocessable_entity }
      end
    end
  end

  def update_all
    params[:artist_fact].each do |id, updated_fact|
      fact = ArtistFact.find id
      fact.update_attributes updated_fact
    end
    redirect_to artist_facts_path
  end

  # DELETE /artist_facts/1
  # DELETE /artist_facts/1.json
  def destroy
    @artist_fact = ArtistFact.find(params[:id])
    @artist_fact.destroy

    respond_to do |format|
      format.html { redirect_to artist_facts_url }
      format.json { head :no_content }
    end
  end
end

06-rails/tunr/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
end

06-rails/tunr/app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
  end

  def create
    user = User.find_by_name params[:username]
    if user.present? && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path
    else
      flash[:notice] = "Incorrect login: Try Again."
      redirect_to login_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

06-rails/tunr/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :check_if_logged_in, :except => [:new, :create]
  before_filter :check_if_admin, :only => [:index, :destroy]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new params[:user]

    if @user.save
      session[:user_id] = @user.id
      # You can pre-create these things for later editing.
      # fact1 = ArtistFact.create(:artist_id => @user.id)
      # fact2 = ArtistFact.create(:artist_id => @user.id)
      # fact3 = ArtistFact.create(:artist_id => @user.id)
      # fact4 = ArtistFact.create(:artist_id => @user.id)
      # fact5 = ArtistFact.create(:artist_id => @user.id)

      redirect_to root_path
    else
      render :new
    end
  end

  def weatherreport
  end

  def edit
    @user = @authenticated
    render :new
  end

  def update
    @user = @authenticated
    if @user.update_attributes params[:user]
      redirect_to root_path
    else
      render :new
    end
  end

  private
  def check_if_logged_in
    redirect_to(root_path) unless @authenticated.present?
  end

  def check_if_admin
    redirect_to(root_path) unless @authenticated.present? && @authenticated.is_admin?
  end
end

06-rails/tunr/app/helpers/application_helper.rb
module ApplicationHelper
  def authentication_menu
    # Build a list of links depending on the user's permissions.
    links = ""
    if @authenticated.present?
      if @authenticated.is_admin
        links += "<li>#{link_to("Show Users", users_path)}</li>"
      end
      links += "<li>#{ link_to('Edit Profile', edit_users_path )}</li>"
      links += "<li>#{ link_to('Logout ' + @authenticated.name, login_path, :method => 'delete',
                      :confirm => 'Are you sure?') }</li>"
    else
      links += "<li>#{ link_to('Login', login_path) }</li>"
    end

    links
  end
end

06-rails/tunr/app/helpers/artist_facts_helper.rb
module ArtistFactsHelper
end

06-rails/tunr/app/views/artist_facts/_form.html.erb
<%= form_for(@artist_fact) do |f| %>
  <% if @artist_fact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@artist_fact.errors.count, "error") %> prohibited this artist_fact from being saved:</h2>

      <ul>
      <% @artist_fact.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :fact %><br />
    <%= f.text_area :fact %>
  </div>
  <div class="field">
    <%= f.label :website %><br />
    <%= f.text_area :website %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

06-rails/tunr/app/views/artist_facts/edit.html.erb
<h1>Editing artist_fact</h1>

<%= render 'form' %>

<%= link_to 'Show', @artist_fact %> |
<%= link_to 'Back', artist_facts_path %>

06-rails/tunr/app/views/artist_facts/edit_all.html.erb
<%= form_tag '/artist_facts/update_all', :method => 'post' do %>
  <% @artist_facts.each do |artist_fact| %>
    <%= fields_for 'artist_fact[]', artist_fact do |f| %>
      <div class="form-group">
        <%= f.label :fact %>
        <%= f.text_field :fact %>
      </div>
      <div class="form-group">
        <%= f.label :website %>
        <%= f.text_field :website %>
      </div>
    <% end %>
  <% end %>
  <%= submit_tag %>
<% end %>

06-rails/tunr/app/views/artist_facts/index.html.erb
<h1>Listing artist_facts</h1>

<table>
  <tr>
    <th>Fact</th>
    <th>Website</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @artist_facts.each do |artist_fact| %>
  <tr>
    <td><%= artist_fact.fact %></td>
    <td><%= artist_fact.website %></td>
    <td><%= link_to 'Show', artist_fact %></td>
    <td><%= link_to 'Edit', edit_artist_fact_path(artist_fact) %></td>
    <td><%= link_to 'Destroy', artist_fact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Artist fact', new_artist_fact_path %>
<%= link_to 'Edit all artist facts', edit_all_artist_facts_path %>

06-rails/tunr/app/views/artist_facts/new.html.erb
<h1>New artist_fact</h1>

<%= render 'form' %>

<%= link_to 'Back', artist_facts_path %>

06-rails/tunr/app/views/artist_facts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Fact:</b>
  <%= @artist_fact.fact %>
</p>

<p>
  <b>Website:</b>
  <%= @artist_fact.website %>
</p>


<%= link_to 'Edit', edit_artist_fact_path(@artist_fact) %> |
<%= link_to 'Back', artist_facts_path %>

06-rails/tunr/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tunr</title>
  <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/normalize/2.1.3/normalize.min.css">
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Tunr', root_path, :class => 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li><%= link_to('Create Account', new_user_path) %></li>
        <%== authentication_menu %>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</div>



  <div class="container">
    <div class="row">
      <div class="col-md-9">
        <% if flash[:notice].present? %>
          <p>
          <%= flash[:notice] %>
          </p>
        <% end %>
        <%= yield %>
      </div>
      <div class="col-md-3">
        <aside class="about">
          <h1>BOLD CORPORATE LOGO</h1>
          <p>Tunr has been providing lorem ipsum aids aids aids</p>
          <ul>
            <% (1..10).to_a.each do |link| %>
              <li><%= link_to "Link #{link}", root_path %></li>
            <% end %>
          </ul>
        </aside>
      </div>
    </div>
  </div>

</body>
</html>